USE LearnFlowERP;
GO

SET IDENTITY_INSERT Permissions ON;

INSERT INTO Permissions (PermissionId, Name) VALUES
(1,'CreateStudent'),
(2,'ViewStudent'),
(3,'UpdateStudent'),
(4,'DeleteStudent'),
(5,'CreateUser'),
(6,'ViewUser'),
(7,'UpdateUser'),
(8,'DeleteUser'),
(9,'CreateEmployee'),
(10,'ViewEmployee'),
(11,'UpdateEmployee'),
(12,'DeleteEmployee'),
(13,'AssignCourse'),
(14,'ViewCourse'),
(15,'CreateDesignation'),
(16,'ViewDesignation'),
(17,'UpdateDesignation'),
(18,'DeleteDesignation'),
(19,'AssignTeacherCourse'),
(20,'ViewTeacherCourse'),
(21,'CreateCourse'),
(22,'UpdateCourse'),
(23,'DeleteCourse'),
(24,'MarkStudentAttendance'),
(25,'ViewStudentAttendance'),
(26,'MarkEmployeeAttendance'),
(27,'ViewEmployeeAttendance'),
(28,'CreateFee'),
(29,'ViewFee'),
(30,'UpdateFee'),
(31,'DeleteFee'),
(32,'CreatePayment'),
(33,'ViewPayment'),
(34,'ViewFinanceDashboard'),
(35,'CreateRefund'),
(36,'ApproveRefund'),
(37,'ManageScholarship'),
(38,'ManageScholarship'),
(39,'ViewScholarship'),
(40,'CreateRefund'),
(41,'ViewRefund'),
(42,'ViewFinanceDashboard'),
(43,'ViewFinanceReports'),
(44,'ViewFinanceStatement'),
(45,'SendFeeReminder'),
(46,'ViewFeeReminder'),
(47,'ViewNotification'),
(48,'CreateNotification'),
(49,'ManageNotification'),
(50,'SendFeeReminder'),
(51,'ViewFeeReminder'),
(10045,'ManagePermissions');

SET IDENTITY_INSERT Permissions OFF;
GO